Repository w3c/w3c.github.io, pull requests merged in 2018-10, with the labels that each got.

#53 add repo-type to identify the type and purpose of the repositories
  w3c.json.html
Labels: enhancement

#51 GH best practices: mention all notification channels
  best-practices.html
Labels: best practices, enhancement

#55 Fix usage of <pre> in several places
  specs.html
  w3c.json.html
  workflow.html
Labels: bug, enhancement
